spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hikari:
      connection-test-query: select 1
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true