spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hikari:
      connection-test-query: select 1
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  security:
    user:
      name: admin
      password: $2a$10$6pZZSQdXesumcyu7SNmjtuItu1tMQ1Z7QgAOlB/MjLldbcDvuY6b6
logging:
  file:
    name: store.log
  logback:
    rollingpolicy:
      file-name-pattern: store-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
      total-size-cap: 1MB
      max-history: 14
      clean-history-on-start: true
