server:
  port: 80
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hikari:
      connection-test-query: select 1
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  thymeleaf:
    cache: false
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

  file:
    name: logs/store.log
  logback:
    rollingpolicy:
      file-name-pattern: store-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
      total-size-cap: 1MB
      max-history: 14
      clean-history-on-start: true
