CREATE TABLE genre (
  id BIGINT AUTO_INCREMENT NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_genre PRIMARY KEY (id)
);


ALTER TABLE book
ADD COLUMN genre_id BIGINT;

ALTER TABLE book ADD CONSTRAINT FK_BOOK_ON_GENRE FOREIGN KEY (genre_id) REFERENCES genre (id);

